### ISSUE TITLE
Create holding page

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/website-GMC#1]
# Summary
Create a new holding page to replace the page at: https://www.globalmediacampaign.org/. Flowmapp for the planned entire site can be found here: https://app.flowmapp.com/projects/16433

# Layout
Follow design from [Bean about Town](https://www.beanabouttown.com/) / [Medes](https://holistic-website.firebaseapp.com/static/library/Medes/medes.modulemedia.co.uk/index.html) with brand colours (#941C55)

1. Counter – A single counter at this stage, of our combined reach as per the website breakdown page - https://docs.google.com/document/d/1hQx6Nlanghv9E6t9KYlS200nSZo97adY2GdFqkaM-NU/edit

2. Twitter Feed - as live along the right hand side - https://twitter.com/GMCEndFGM

3. Strong photograph – as background - ifrah with camera - attached

4. Video – Sadia - https://www.youtube.com/watch?v=ZaA-e3quO1M - with play button centre, which i think comes automatically when you run the video from You Tube. If possible would be great to have that play button in our brand colours.  And lead in text above that says: 
“Click here to see how women like Sadia are working with their religious leaders to end FGM in their communities”

5. Mission Statement - 
Mission statement: Ending Female Genital Mutilation Through the Power of the Media 
We are the Global Media Campaign to EndFGM.  We train, support and fund anti-FGM activists across Africa (mostly women) to put the influential voices of religious and traditional leaders on local radio, TV and social media to accelerate the end of FGM.

End goal is to show the info in this google doc: https://docs.google.com/document/d/1hQx6Nlanghv9E6t9KYlS200nSZo97adY2GdFqkaM-NU/edit

**Comment by andrewlew1s** [comment]
https://stackoverflow.com/questions/32627887/youtube-custom-play-icon?noredirect=1&lq=1

**Comment by michaelfitzhavey** [comment]
@andrewlew1s that's sweet, awesome find - would be very exciting to have our own implementation of that

**Comment by michaelfitzhavey** [comment]
fixed with release 0.0.2
