### ISSUE TITLE
Update website text

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/website-gmc#36]
# Landing Page
- [x] Landing image text to shorted back to `FGM` from `female genital mutilation`
- [x] Update landing image to original image of Ifrah (in the `/images` folder)
- [x] Remove `(mostly women)` from intro text

# Strategy Page
- [x] update image of Lucy to:
![Lucy_Ganda](https://user-images.githubusercontent.com/2746248/55325923-5fb7bc00-547e-11e9-9011-bb68036e21b4.jpg)

# About Page
- [x] Mary's (backroom team) job description to be set to `Social and multimedia producer`

**Comment by andrewlew1s** [comment]
Completed, are we sure about the landing pic change?

**Comment by michaelfitzhavey** [comment]
Make changes on a separate branch and submit PRs for review if possible xo
